#!/bin/bash
#

#include functions.
. functions_pub

#check privilidge.
if [ $UID != 0 ]; then
	echo "Please run with root privilidge."
	exit 1
fi

#setup chroot for build base system
mkdir -pv ${CLFS}/{dev,proc,sys}
mountpoint -q ${CLFS}/proc || mount -vt proc proc ${CLFS}/proc
mountpoint -q ${CLFS}/sys || mount -vt sysfs sysfs ${CLFS}/sys
[ -e ${CLFS}/dev/console ] || mknod -m 600 ${CLFS}/dev/console c 5 1
[ -e ${CLFS}/dev/null ] || mknod -m 666 ${CLFS}/dev/null c 1 3
mountpoint -q ${CLFS}/dev || mount -v -o bind /dev ${CLFS}/dev
mountpoint -q ${CLFS}/dev/shm || mount -f -vt tmpfs tmpfs ${CLFS}/dev/shm
mountpoint -q ${CLFS}/dev/pts || mount -f -vt devpts -o gid=4,mode=620 devpts ${CLFS}/dev/pts

chroot "${CLFS}" /tools/bin/env -i \
	HOME=/root TERM="${TERM}" PS1='\u:\w\$ ' \
	PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin \
	/tools/bin/bash --login +h

#run in-chroot in chroot environment.
cp -v "in-chroot" "${CLFS}"
