#!/bin/bash

. functions_pub

PackageName=ppl-0.11.2
PackageURL=http://www.cs.unipr.it/ppl/Download/ftp/releases/0.11.2/ppl-0.11.2.tar.bz2


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#unpack
        unpack_and_enter $PackageName $PackageURL $(basename $0)

	#configure	
	CC="${CC} ${BUILD64}" ./configure --prefix=/tools \
	    --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	    --enable-interfaces="c,cxx" --libdir=/tools/lib64 --enable-shared \
	    --disable-optimization --with-libgmp-prefix=/tools \
	    --with-libgmpxx-prefix=/tools
	err_check "[Error] configure $PackageName failed."

	#When PPL is cross-compiled, it does not check whether GMP was compiled with support for exceptions, and simply assumes it was not. This assumption is incorrect, so we will fix that:
	echo '#define PPL_GMP_SUPPORTS_EXCEPTIONS 1' >> confdefs.h

	#make
	$MAKE
	err_check "[Error] make $PackageName failed."	

	#install
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL $(basename $0)
	;;

*)
	exit 1
	;;
esac

#end 

