#!/bin/bash

. functions_pub

PackageName=cloog-ppl-0.15.11
PackageURL=ftp://gcc.gnu.org/pub/gcc/infrastructure/cloog-ppl-0.15.11.tar.gz


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#unpack
        unpack_and_enter $PackageName $PackageURL $(basename $0)

	#The following prevents the configure script from setting LD_LIBRARY_PATH when it finds PPL. This will prevent any conflicts with libraries from the host system:
	cp -v configure{,.orig}
	sed -e "/LD_LIBRARY_PATH=/d" configure.orig > configure
	err_check "[Error] $PackageName sed failed."
	
	#configure
	CC="${CC} ${BUILD64}" ./configure --prefix=/tools \
	    --build=${CLFS_HOST} --host=${CLFS_TARGET} --with-bits=gmp \
	    --libdir=/tools/lib64 --enable-shared \
	    --with-gmp=/tools --with-ppl=/tools
	err_check "[Error] configure $PackageName failed."

	#make
	$MAKE
	err_check "[Error] make $PackageName failed."	

	#install
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory
	package_leave $PackageName $PackageURL $(basename $0)
	;;

*)
	exit 1
	;;
esac

#end 

