#!/bin/bash

. functions_pub

PackageName=binutils-2.21.1
PackageURL=http://ftp.gnu.org/gnu/binutils/binutils-2.21.1a.tar.bz2


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#unpack
        unpack_and_enter $PackageName $PackageURL $(basename $0)

	#The Binutils documentation recommends building Binutils outside of the source directory in a dedicated build directory:
	mkdir -v binutils-build
	cd binutils-build
	
	#configure
	CC="${CC} ${BUILD64}" ../configure \
	    --prefix=/tools --libdir=/tools/lib64 --with-lib-path=/tools/lib64:/tools/lib \
	    --build=${CLFS_HOST} --host=${CLFS_TARGET} --target=${CLFS_TARGET} \
            --disable-nls --enable-shared --enable-64-bit-bfd
	err_check "[Error] configure $PackageName failed."

	#make
	make configure-host
	err_check "[Error] $PackageName make configure-host failed."	
	
	$MAKE
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory
	package_leave $PackageName $PackageURL $(basename $0)
	;;

*)
	exit 1
	;;
esac

#end 

