#!/bin/bash

. functions_pub

PackageName=gcc-4.6.3
PackageURL=ftp://gcc.gnu.org/pub/gcc/releases/gcc-4.6.3/gcc-4.6.3.tar.bz2

case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#unpack
        unpack_and_enter $PackageName $PackageURL $(basename $0)

	#The following patch contains a number of updates to the 4.6.3 branch by the GCC developers:
	patch -Np1 -i $PATCHES/gcc-4.6.3-branch_update-1.patch
	err_check "[Error] patch $PackageName failed."

	#Make a couple of essential adjustments to the specs file to ensure GCC uses our build environment:
	patch -Np1 -i $PATCHES/gcc-4.6.3-specs-1.patch
	err_check "[Error] patch $PackageName failed."

	#Change the StartFile Spec and Standard Include Dir so that GCC looks in /tools:
	echo -en '#undef STANDARD_INCLUDE_DIR\n#define STANDARD_INCLUDE_DIR "/tools/include/"\n\n' >> gcc/config/linux.h
echo -en '\n#undef STANDARD_STARTFILE_PREFIX_1\n#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"\n' >> gcc/config/linux.h
echo -en '\n#undef STANDARD_STARTFILE_PREFIX_2\n#define STANDARD_STARTFILE_PREFIX_2 ""\n' >> gcc/config/linux.h	

	#Also, we need to set the directory searched by the fixincludes process for system headers, so it won't look at the host's headers:
	cp -v gcc/Makefile.in{,.orig}
	sed -e 's@\(^NATIVE_SYSTEM_HEADER_DIR =\).*@\1 /tools/include@g' \
	    gcc/Makefile.in.orig > gcc/Makefile.in
	err_check "[Error] sed $PackageName failed."
	
	#configure
	mkdir -v gcc-build
	cd gcc-build
	
	CC="${CC} ${BUILD64}" CXX="${CXX} ${BUILD64}" \
	  ../configure --prefix=/tools \
	  --libdir=/tools/lib64 --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --target=${CLFS_TARGET} --with-local-prefix=/tools  --enable-long-long \
	  --enable-c99 --enable-shared --enable-threads=posix \
	  --enable-__cxa_atexit --disable-nls --enable-languages=c,c++ \
	  --disable-libstdcxx-pch --enable-cloog-backend=isl	
	err_check "[Error] configure $PackageName failed."

	#The following will prevent GCC from looking in the wrong directories for headers and libraries:
	cp -v Makefile{,.orig}
	sed "/^HOST_\(GMP\|PPL\|CLOOG\)\(LIBS\|INC\)/s:-[IL]/\(lib\|include\)::" \
    		Makefile.orig > Makefile	

	#make
	$MAKE AS_FOR_TARGET="${AS}" LD_FOR_TARGET="${LD}"
	err_check "[Error] make $PackageName failed."	

	#install
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL $(basename $0)
	;;

*)
	exit 1
	;;
esac

#end 

