#!/bin/bash

. functions_pub

PackageName=bash-4.2
PackageURL=http://ftp.gnu.org/gnu/bash/bash-4.2.tar.gz


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#unpack
        unpack_and_enter $PackageName $PackageURL $(basename $0)

	#The following patch contains updates from the maintainer. The maintainer of Bash only releases these patches to fix serious issues:
	patch -Np1 -i $PATCHES/bash-4.2-branch_update-2.patch

	#When Bash is cross-compiled, it cannot test for the presence of named pipes, among other things. If you used su to become an unprivileged user, this combination will cause Bash to build without process substitution, which will break one of the C++ test scripts in eglibc. The following prevents future problems by skipping the check for named pipes, as well as other tests that can not run while cross-compiling or that do not run properly:
	cat > config.cache << "EOF"
ac_cv_func_mmap_fixed_mapped=yes
ac_cv_func_strcoll_works=yes
ac_cv_func_working_mktime=yes
bash_cv_func_sigsetjmp=present
bash_cv_getcwd_malloc=yes
bash_cv_job_control_missing=present
bash_cv_printf_a_format=yes
bash_cv_sys_named_pipes=present
bash_cv_ulimit_maxfds=yes
bash_cv_under_sys_siglist=yes
bash_cv_unusable_rtsigs=no
gt_cv_int_divbyzero_sigfpe=yes
EOF
	
	#configure
	CC="${CC} ${BUILD64}" CXX="${CXX} ${BUILD64}" \
	   ./configure --prefix=/tools \
	    --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	    --without-bash-malloc --cache-file=config.cache
	err_check "[Error] configure $PackageName failed."

	#make
	$MAKE
	err_check "[Error] make $PackageName failed."	

	#install
	make install
	err_check "[Error] install $PackageName failed."

	#Make a link for programs that use sh for a shell:
	ln -sv bash /tools/bin/sh

	#leave directory
	package_leave $PackageName $PackageURL $(basename $0)
	;;

*)
	exit 1
	;;
esac

#end 

