#!/bin/bash

. functions_pub

PackageName=bzip2-1.0.6
PackageURL=http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#unpack
        unpack_and_enter $PackageName $PackageURL $(basename $0)

	#Bzip2's default Makefile target automatically runs the testsuite as well. We need to remove the tests since they won't work on a multi-architecture build, and change the default lib path to lib64:
	cp -v Makefile{,.orig}
	sed -e 's@^\(all:.*\) test@\1@g' \
	    -e 's@/lib\(/\| \|$\)@/lib64\1@g' Makefile.orig > Makefile

	#The Bzip2 package does not contain a configure script. Compile it with:
	make CC="${CC} ${BUILD64}" AR="${AR}" RANLIB="${RANLIB}"
	err_check "[Error] make $PackageName failed."	

	#install
	make PREFIX=/tools install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL $(basename $0)
	;;

*)
	exit 1
	;;
esac

#end 

