#!/bin/bash

. functions_pub

PackageName=coreutils-8.20
PackageURL=http://ftp.gnu.org/gnu/coreutils/coreutils-8.20.tar.xz

case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#unpack
        unpack_and_enter $PackageName $PackageURL $(basename $0)

	#The following command updates the timestamps on the uname and hostname man pages so that the Makefile does not attempt to regenerate them:
	touch man/uname.1 man/hostname.1

	#Configure can not properly determine how to get free space when cross-compiling - as a result, the df program will not be built. Add the following entries to config.cache to correct this, and fix various cross-compiling issues:
	cat > config.cache << EOF
fu_cv_sys_stat_statfs2_bsize=yes
gl_cv_func_working_mkstemp=yes
EOF
	#configure
	CC="${CC} ${BUILD64}" ./configure --prefix=/tools \
 	   --build=${CLFS_HOST} --host=${CLFS_TARGET} \
 	   --enable-install-program=hostname --cache-file=config.cache
	err_check "[Error] configure $PackageName failed."

	#Coreutils does not build make-prime-list properly and the host cannot execute it. We build it using the host compiler so it can be executed for the generation of data required for the build.
	cp -v Makefile{,.orig}
	sed '/src_make_prime_list/d' Makefile.orig > Makefile
	depbase=`echo src/make-prime-list.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -m64 -std=gnu99  -I. -I./lib  -Ilib -I./lib -Isrc -I./src \
	    -fdiagnostics-show-option -funit-at-a-time -g -O2 -MT \
	    src/make-prime-list.o -MD -MP -MF $depbase.Tpo -c -o src/make-prime-list.o \
	    src/make-prime-list.c &&
	mv -f $depbase.Tpo $depbase.Po
	gcc -m64 -std=gnu99 -fdiagnostics-show-option -funit-at-a-time -g -O2 \
	    -Wl,--as-needed  -o src/make-prime-list src/make-prime-list.o

	#Remove the building of the hostname man page as it is affected by the previous commands.
	cp -v Makefile{,.bak}
	sed -e '/hostname.1/d' Makefile.bak > Makefile

	#make
	$MAKE
	err_check "[Error] make $PackageName failed."	

	#install
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL $(basename $0)
	;;

*)
	exit 1
	;;
esac

#end 

