#!/bin/bash

. functions_pub

PackageName=coreutils-8.12
PackageURL=http://ftp.gnu.org/gnu/coreutils/coreutils-8.12.tar.gz


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#unpack
        unpack_and_enter $PackageName $PackageURL $(basename $0)

	#The following command updates the timestamps on the uname and hostname man pages so that the Makefile does not attempt to regenerate them:
	touch man/uname.1 man/hostname.1

	#Configure can not properly determine how to get free space when cross-compiling - as a result, the df program will not be built. Add the following entries to config.cache to correct this, and fix various cross-compiling issues:
	cat > config.cache << EOF
fu_cv_sys_stat_statfs2_bsize=yes
gl_cv_func_working_mkstemp=yes
EOF
	#configure
	CC="${CC} ${BUILD64}" ./configure --prefix=/tools \
	    --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	    --enable-install-program=hostname --cache-file=config.cache
	err_check "[Error] configure $PackageName failed."

	#make
	$MAKE
	err_check "[Error] make $PackageName failed."	

	#install
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL $(basename $0)
	;;

*)
	exit 1
	;;
esac

#end 

