#!/bin/bash

. functions_pub

PackageName=gettext-0.18.1.1
PackageURL=http://ftp.gnu.org/gnu/gettext/gettext-0.18.1.1.tar.gz

case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#unpack
        unpack_and_enter $PackageName $PackageURL $(basename $0)

	#Only the programs in the gettext-tools directory need to be installed for the temp-system:
	cd gettext-tools

	#When cross-compiling the Gettext configure script assumes we don't have a working wcwidth when we do. The following will fix possible compilation errors because of this assumption:
	echo "gl_cv_func_wcwidth_works=yes" > config.cache	

	#configure
	CC="${CC} ${BUILD64}" CXX="${CXX} ${BUILD64}" \
	    ./configure --prefix=/tools --disable-shared \
	    --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	    --cache-file=config.cache
	err_check "[Error] configure $PackageName failed."

	#make
	$MAKE -C gnulib-lib
	$MAKE -C src msgfmt
	err_check "[Error] make $PackageName failed."	

	#Install the msgfmt binary:
	cp -v src/msgfmt /tools/bin
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL $(basename $0)
	;;

*)
	exit 1
	;;
esac

#end 

