#!/bin/bash

. functions_pub

PackageName=make-3.82
PackageURL=http://ftp.gnu.org/gnu/make/make-3.82.tar.bz2

case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#unpack
        unpack_and_enter $PackageName $PackageURL $(basename $0)

	#configure
	CC="${CC} ${BUILD64}" ./configure --prefix=/tools \
	   --build=${CLFS_HOST} --host=${CLFS_TARGET}
	err_check "[Error] configure $PackageName failed."

	#make
	$MAKE
	err_check "[Error] make $PackageName failed."	

	#install
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL $(basename $0)
	;;

*)
	exit 1
	;;
esac

#end 

