#!/bin/bash

. functions_pub

PackageName=patch-2.7.1
PackageURL=http://ftp.gnu.org/gnu/patch/patch-2.7.1.tar.xz

case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#unpack
        unpack_and_enter $PackageName $PackageURL $(basename $0)

	#When cross-compiling configure cannot properly detect the existance of certain features. Override this behaviour:
	echo "ac_cv_func_strnlen_working=yes" > config.cache

	#configure
	CC="${CC} ${BUILD64}" ./configure --prefix=/tools \
	    --build=${CLFS_HOST} --host=${CLFS_TARGET} \
    	    --cache-file=config.cache
	err_check "[Error] configure $PackageName failed."

	#make
	$MAKE
	err_check "[Error] make $PackageName failed."	

	#install
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL $(basename $0)
	;;

*)
	exit 1
	;;
esac

#end 

