#!/bin/bash

. functions_pub

PackageName=util-linux-2.22.1
PackageURL=http://www.kernel.org/pub//linux/utils/util-linux/v2.22/util-linux-2.22.1.tar.xz

case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#unpack
        unpack_and_enter $PackageName $PackageURL $(basename $0)

	#Util-linux cannot test for scanf type modifiers when cross compiling and stops. We can issue the following to instruct it to use the one we've compiled.
	echo "scanf_cv_type_modifier=as" > config.cache

	#configure
	CC="${CC} ${BUILD64}" ./configure --prefix=/tools \
    		--build=${CLFS_HOST} --host=${CLFS_TARGET} \
    		--disable-makeinstall-chown --disable-login --disable-su \
   	 	--config-cache
	err_check "[Error] configure $PackageName failed."

	#make
	$MAKE
	err_check "[Error] make $PackageName failed."	

	#install
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL $(basename $0)
	;;

*)
	exit 1
	;;
esac

#end 

