#!/bin/bash

. functions_pub

PackageName=linux-3.4.17
PackageURL=http://www.kernel.org/pub/linux/kernel/v3.0/linux-3.4.17.tar.xz

case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
        unpack_and_enter $PackageName $PackageURL $(basename $0)

	#Install the kernel header files:
	install -dv /tools/include
	make mrproper
	err_check "[Error] $PackageName make mrproper failed."
	make ARCH=x86_64 headers_check
	err_check "[Error] $PackageName make ARCH=x86_64 headers_check failed."
	make ARCH=x86_64 INSTALL_HDR_PATH=dest headers_install
	err_check "[Error] $PackageName make ARCH=x86_64 INSTALL_HDR_PATH=dest headers_install failed."
	cp -rv dest/include/* /tools/include
	
	#leave directory.
	package_leave $PackageName $PackageURL $(basename $0)
	;;

*)
	exit 1
	;;
esac

#end 

