#!/bin/bash

. functions_pub

PackageName=file-5.07
PackageURL=ftp://ftp.astron.com/pub/file/file-5.07.tar.gz


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
        unpack_and_enter $PackageName $PackageURL $(basename $0)

	#configure	
	./configure --prefix=/cross-tools
	err_check "[Error] configure $PackageName failed."

	#make
	$MAKE
	err_check "[Error] make $PackageName failed."	

	#install
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory
	package_leave $PackageName $PackageURL $(basename $0)
	;;

*)
	exit 1
	;;
esac

#end 

