#!/bin/bash

. functions_pub

PackageName=mpc-0.9
PackageURL=http://www.multiprecision.org/mpc/download/mpc-0.9.tar.gz


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#unpack
        unpack_and_enter $PackageName $PackageURL $(basename $0)

	#configure	
	LDFLAGS="-Wl,-rpath,/cross-tools/lib" \
	./configure --prefix=/cross-tools \
	    --with-gmp=/cross-tools \
	    --with-mpfr=/cross-tools
	err_check "[Error] configure $PackageName failed."

	#make
	$MAKE
	err_check "[Error] make $PackageName failed."	

	#install
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL $(basename $0)
	;;

*)
	exit 1
	;;
esac

#end 

