#!/bin/bash

. functions_pub

PackageName=cloog-0.16.3
PackageURL=http://www.bastoul.net/cloog/pages/download/cloog-0.16.3.tar.gz	

case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#unpack
        unpack_and_enter $PackageName $PackageURL $(basename $0)

	#The following prevents the configure script from setting LD_LIBRARY_PATH when it finds PPL. This will prevent any conflicts with libraries from the host system:
	cp -v configure{,.orig}
	sed -e "/LD_LIBRARY_PATH=/d" configure.orig > configure
	err_check "[Error] $PackageName sed failed."
	
	#configure
	LDFLAGS="-Wl,-rpath,/cross-tools/lib" \
	./configure --prefix=/cross-tools --enable-shared --disable-static --with-gmp-prefix=/cross-tools
	err_check "[Error] configure $PackageName failed."

	#make
	$MAKE
	err_check "[Error] make $PackageName failed."	

	#install
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory
	package_leave $PackageName $PackageURL $(basename $0)
	;;

*)
	exit 1
	;;
esac

#end 

