#!/bin/bash

. functions_pub

PackageName=gcc-4.6.3
PackageURL=ftp://gcc.gnu.org/pub/gcc/releases/gcc-4.6.3/gcc-4.6.3.tar.bz2

case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL $(basename $0)

	# patch contains a number of updates to the 4.6.3 branch by the GCC developers:
	patch -Np1 -i $PATCHES/gcc-4.6.3-branch_update-1.patch
	err_check "[Error] patch $PackageName failed."

	#Make a couple of essential adjustments to the specs file to ensure GCC uses our build environment:
	patch -Np1 -i $PATCHES/gcc-4.6.3-specs-1.patch
	err_check "[Error] patch $PackageName failed."

	#Change the StartFile Spec and Standard Include Dir so that GCC looks in /tools:
	echo -en '#undef STANDARD_INCLUDE_DIR\n#define STANDARD_INCLUDE_DIR "/tools/include/"\n\n' >> gcc/config/linux.h
echo -en '\n#undef STANDARD_STARTFILE_PREFIX_1\n#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"\n' >> gcc/config/linux.h
echo -en '\n#undef STANDARD_STARTFILE_PREFIX_2\n#define STANDARD_STARTFILE_PREFIX_2 ""\n' >> gcc/config/linux.h

	#Now alter gcc's c preprocessor's default include search path to use /tools only:
	cp -v gcc/Makefile.in{,.orig}
	sed -e "s@\(^CROSS_SYSTEM_HEADER_DIR =\).*@\1 /tools/include@g" \
    gcc/Makefile.in.orig > gcc/Makefile.in
	err_check "[Error] sed $PackageName failed."
	
	#We will create a dummy limits.h so the build will not use the one provided by the host distro:
	touch /tools/include/limits.h

	#configure
	mkdir -v gcc-build
	cd gcc-build

	AR=ar LDFLAGS="-Wl,-rpath,/cross-tools/lib" \
	  ../configure --prefix=/cross-tools \
		  --build=${CLFS_HOST} --host=${CLFS_HOST} --target=${CLFS_TARGET} \
		  --with-sysroot=${CLFS} --with-local-prefix=/tools --disable-nls \
		  --disable-shared --disable-static --with-mpfr=/cross-tools \
		  --with-gmp=/cross-tools --with-ppl=/cross-tools --with-cloog=/cross-tools \
		  --without-headers --with-newlib --disable-decimal-float \
		  --disable-libgomp --disable-libmudflap --disable-libssp \
		  --disable-threads --enable-languages=c --enable-cloog-backend=isl
	err_check "[Error] configure $PackageName failed."

	#make.
	$MAKE all-gcc all-target-libgcc
	err_check "[Error] make $PackageName failed."	

	#install.
	make install-gcc install-target-libgcc
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL $(basename $0)
	;;

*)
	exit 1
	;;
esac

#end 

